apiVersion: apps/v1
kind: Deployment
metadata:
  name: imcworkshop
spec:
  replicas: 10
  selector:
    matchLabels:
      app: imcworkshop
  template:
    metadata:
      labels:
        app: imcworkshop
    spec:
      containers:
      - name: imcworkshop-server
        image: ghcr.io/potjamanp/imcworkshop
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: imcworkshop-service
  labels:
    app: imcworkshop-service
spec:
  selector:
    app: imcworkshop
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP