apiVersion: apps/v1
kind: Deployment
metadata:
  name: user15
spec:
  replicas: 10
  selector:
    matchLabels:
      app: user15
  template:
    metadata:
      labels:
        app: user15
    spec:
      containers:
      - name: user15-server
        image: ghcr.io/potjamanp/imcworkshop
        PullImagePolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user15-service
  labels:
    app: user15-service
spec:
  selector:
    app: user15
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP